default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: portal
  password: portal
  port: 5432
  host: localhost

development:
  <<: *default
  database: resume_parser_development

test:
  <<: *default
  database: resume_parser_test

production:
  <<: *default
  database: resume_parser_production
