source 'https://rubygems.org'

ruby '3.2.2'
gem 'rails', '~> 8.0'

gem 'pg'
gem 'pry'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'bootsnap', require: false

gem 'json'
gem 'pdf-reader'
gem 'rack-cors'

gem 'docx'
gem "bcrypt", "~> 3.1.7"
gem 'httparty'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
